name: LighthouseCI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-22.04
    steps:
      - name: Set env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            fake_git_commit_hash=$(echo "$(date +%s)" | sha1sum | cut -b -40)
            echo "Fake git commit hash set to ${fake_git_commit_hash}"
            echo "LHCI_BUILD_CONTEXT__CURRENT_HASH=${fake_git_commit_hash}" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.29.1
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.15.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build project
        run: pnpm build
      - name: Collect lighthouse reports
        run: pnpm lhci collect
      - name: Assert on lighthouse reports
        run: pnpm lhci assert
      - name: Upload lighthouse reports to lhci server
        run: pnpm lhci upload --basicAuth.username=admin --basicAuth.password=password
